[[redirects]]
  from = "/go"
  to = "/?utm_source=school&utm_medium=printedskfbrochure&utm_campaign=studentbrochure"

[[redirects]]
  from = "/accepted"
  to = "/"

[[redirects]]
  from = "/designer-track"
  to = "/"

[[redirects]]
  from = "/web-developer-track"
  to = "/"
